export const NAUTICAL_COLORS = {
  parchment: "#f2efe9",
  parchmentDark: "#e8e5df",
  land: "#4a9de0",
  landStroke: "#3b8ad4",
  waterLight: "#f2efe9",
  waterMid: "#f2efe9",
  waterDeep: "#f2efe9",
  gridLine: "#c8c5bf",
  compassDark: "#3d3d3d",
  compassLight: "#999999",
  portDefault: "#666666",
  portSelected: "#ea4335",
  portHover: "#fbbc04",
  portLabel: "#333333",
  routeLine: "#1a3a5c",
  routeArrow: "#1a3a5c",
  labelSerif: "Georgia, 'Times New Roman', serif",
  labelSans: "'Geist', sans-serif",
} as const;

export const MAP_CONFIG = {
  defaultWidth: 960,
  defaultHeight: 600,
  padding: 20,
  projectionParallels: [42, 48] as [number, number],
  projectionRotate: [84, 0] as [number, number],
  graticuleExtent: [[-93, 41], [-75, 50]] as const,
  graticuleStep: [2, 2] as [number, number],
} as const;
